version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    govet:
      enable:
        - atomicalign
      settings:
        printf:
          funcs:
            - (github.com/sirupsen/logrus.FieldLogger).Debugf
            - (github.com/sirupsen/logrus.FieldLogger).Infof
            - (github.com/sirupsen/logrus.FieldLogger).Printf
            - (github.com/sirupsen/logrus.FieldLogger).Warnf
            - (github.com/sirupsen/logrus.FieldLogger).Warningf
            - (github.com/sirupsen/logrus.FieldLogger).Errorf
            - (github.com/sirupsen/logrus.FieldLogger).Fatalf
            - (github.com/sirupsen/logrus.FieldLogger).Panicf
    revive:
      rules:
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - preserveScope
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: true
        - name: identical-branches
          severity: error
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: import-alias-naming
          severity: warning
          disabled: true
        - name: modifies-value-receiver
          severity: error
          disabled: false
        - name: package-comments
          severity: warning
          disabled: true
        - name: range
          severity: warning
          disabled: true
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: error
          disabled: false
        - name: redefines-builtin-id
          severity: error
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - .*_test\.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test\.go
      - third_party$
      - builtin$
      - examples$
